user tests
BSU-cool-chat/Backend pull request #74
Opened 2023-05-26 19:33 UTC by Adamenko-Vladislav

2023-05-26 20:03 UTC, AzyavchikovAlex requested changes

2023-05-26 20:03 UTC, AzyavchikovAlex commented on BSU_cool_chat/src/test/add_users.sh
> +echo -e "${Green}Add users ${database} -- all right!\n"
Создай пожалуйста файлик с sql запросами script.sql(например) и запусти только его (psql -U postgres -h localhost bsu_cool_chat_db < script.sql)

2023-05-26 20:03 UTC, AzyavchikovAlex commented on BSU_cool_chat/src/test/empty_database.sh
> +
SQL в отдельный файл

2023-05-26 20:03 UTC, AzyavchikovAlex commented on BSU_cool_chat/src/test/java/project/service/User/UserServiceImplTest.java
> +}
После запуска тестов база данных чистится?

2023-05-26 20:03 UTC, AzyavchikovAlex commented on BSU_cool_chat/src/test/java/project/service/User/UserServiceImplTest.java
> +}
Хотелось бы, чтобы чистилась

2023-05-26 20:03 UTC, AzyavchikovAlex commented on BSU_cool_chat/src/test/add_users.sh
> +echo -e "${Green}Add users ${database} -- all right!\n"
Так читаемей код будет

2023-05-26 21:25 UTC, Adamenko-Vladislav commented on BSU_cool_chat/src/test/add_users.sh
> +echo -e "${Green}Add users ${database} -- all right!\n"
Хороший поинт, но, если я на каждый запрос буду создавать файлик, то их получится > 25

2023-05-26 21:26 UTC, Adamenko-Vladislav commented on BSU_cool_chat/src/test/empty_database.sh
> +
Пока не понимаю к чему коммент, но очень хотел бы понять

2023-05-26 21:35 UTC, Adamenko-Vladislav commented on BSU_cool_chat/src/test/java/project/service/User/UserServiceImplTest.java
> +}
Добавил

2023-05-27 09:22 UTC, AzyavchikovAlex approved these changes

2023-05-27 09:28 UTC, merged